### ISSUE TITLE
Installation breaks on Python 3.6

### ISSUE THREAD

**Issue by luizberti** [kennethreitz/tablib#267]
Ran it both outside and inside a `venv`. It refuses to install and throws the following exception:

```
$ pip install tablib
Collecting tablib
  Using cached tablib-0.11.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/setup.py", line 7, in <module>
        import tablib
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/__init__.py", line 3, in <module>
        from tablib.core import (
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/core.py", line 15, in <module>
        from tablib import formats
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/formats/__init__.py", line 6, in <module>
        from . import _csv as csv
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/formats/_csv.py", line 6, in <module>
        from tablib.compat import is_py3, csv, StringIO
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/compat.py", line 25, in <module>
        import tablib.packages.xlwt3 as xlwt
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/packages/xlwt3/__init__.py", line 5, in <module>
        from .Row import Row
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/packages/xlwt3/Row.py", line 7, in <module>
        from . import ExcelFormula
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/packages/xlwt3/ExcelFormula.py", line 1, in <module>
        from . import ExcelFormulaParser, ExcelFormulaLexer
      File "/private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/tablib/packages/xlwt3/ExcelFormulaLexer.py", line 52, in <module>
        VERBOSE+LOCALE+IGNORECASE)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 233, in compile
        return _compile(pattern, flags)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 562, in compile
        p = sre_parse.parse(p, flags)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 866, in parse
        p.pattern.flags = fix_flags(str, p.pattern.flags)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 833, in fix_flags
        raise ValueError("cannot use LOCALE flag with a str pattern")
    ValueError: cannot use LOCALE flag with a str pattern
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/q0/959r0mm56rxfs98qv69b76qc0000gn/T/pip-build-e19s1qrc/tablib/
```

**Comment by mikeckennedy** [comment]
Hey guys. I ran into this as well. Just want to +1 the issue and watch this thread.

**Comment by luizfb** [comment]
@mikeckennedy you can use `pip install git+https://github.com/kennethreitz/tablib.git` for now.

`master` works fine, it's just the pip version that is wrecked.

**Comment by mikeckennedy** [comment]
@luizfb Thanks for the tip. I saw you mentioned that in another issue and I used it to fix my venv. Will be nice to have an official version out there.

**Comment by kennethreitz** [comment]
let's get master published so this isn't an issue anymore

**Comment by adamzap** [comment]
Looks like @iurisilvio is the PyPI maintainer

**Comment by kennethreitz** [comment]
is this still an issue?

**Comment by adamzap** [comment]
Works great for me!

**Comment by Fingel** [comment]
Just installed the latest version from PyPI, works fine on 3.6.
