### ISSUE TITLE
Import from JSON fails

### ISSUE THREAD

**Issue by TomFaulkner** [kennethreitz/tablib#271]
I am trying to import from json using the file here: http://pastebin.com/5bDUCAch

```
with open('data.json', 'r') as f:
    j = f.read()
    
data = tablib.Dataset().load(j)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python35\lib\site-packages\tablib\core.py", line 449, in load
    import_set(self, in_stream, **kwargs)
  File "C:\Python35\lib\site-packages\tablib\formats\_json.py", line 34, in import_set
    dset.dict = json.loads(in_stream)
  File "C:\Python35\lib\site-packages\tablib\core.py", line 377, in _set_dict
    if isinstance(pickle[0], list):
KeyError: 0
```
```
ds = tablib.Dataset()
ds.json = j
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python35\lib\site-packages\tablib\formats\_json.py", line 34, in import_set
    dset.dict = json.loads(in_stream)
  File "C:\Python35\lib\site-packages\tablib\core.py", line 377, in _set_dict
    if isinstance(pickle[0], list):
KeyError: 0
```
According to http://jsonlint.com/ this is valid json.

Using the simple example on the quick start page works as expected. Also, using json.loads(j) works as expected.

**Comment by mcarans** [comment]
I also get this error with this file: https://cbpfapi.unocha.org/vo1/odata/Contribution

**Comment by bobgott** [comment]
I'm seeing the same error. Need to switch over to json.load() until fixed

**Comment by pernambucano** [comment]
To anyone having this issue, the cause is that the json is not enclosed in brackets (it's not an array). You can see the answer here https://stackoverflow.com/questions/43413253/keyerror-0-in-python. The easiest way to solve this is to transform your now dict(from the json) into an array of dicts with your dict inside.
