### ISSUE TITLE
Exporting huge xls file fails

### ISSUE THREAD

**Issue by Benny-** [kennethreitz/tablib#283]
**Reproducible steps:**
Run this program
```python
#!/usr/bin/env python3

import tablib

data = tablib.Dataset()

for i in range(65537):
    data.append(["This is row", i])


with open('data.xls', 'wb') as f:
    f.write(data.xls)
```

**Expected result:**
A file is created

**Actual result:**
A exception is generated
```
Traceback (most recent call last):
  File "./export_size.py", line 12, in <module>
    f.write(data.xls)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/formats/_xls.py", line 44, in export_set
    dset_sheet(dataset, ws)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/formats/_xls.py", line 133, in dset_sheet
    ws.write(i, j, col)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/packages/xlwt3/Worksheet.py", line 1002, in write
    self.row(r).write(c, label, style)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/packages/xlwt3/Worksheet.py", line 1047, in row
    self.__rows[indx] = self.Row(indx, self)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/packages/xlwt3/Row.py", line 40, in __init__
    raise ValueError("row index (%r) not an int in range(65536)" % rowx)
ValueError: row index (65536) not an int in range(65536)
```

**Used version:**
`tablib.__version__ == '0.11.4'`

**Comment by iurisilvio** [comment]
I think it is a `xls` limitation, not `tablib` or `xlwt` issue. AFAIK, `.xls` spec has a 256 column and 65536 row limit.

It works if you save it as a `xlsx` file.

```python
with open('data.xlsx', 'wb') as f:
    f.write(data.xlsx)
```

**Comment by Benny-** [comment]
.xlsx format works perfectly.
