### ISSUE TITLE
openpyxl changed at 2.5.0 causing this line (semantic) to throw a TypeError exception

### ISSUE THREAD

**Issue by n6151h** [kennethreitz/tablib#331]
https://github.com/kennethreitz/tablib/blob/4c300e65a50eef72b91fa1909c9f68679723955e/tablib/formats/_xlsx.py#L122

The cell method no longer seems to take a single argument (string containing the Excel-ish form of a cell address: e.g. A4 or JJ150)  Instead, it takes two positional args, (row, column), which must be integers > 0.

Here's a jupyter session depicting the error.  (Last line shows correct usage.)

```python
In[42]: ws.cell('A1')
Traceback (most recent call last):
  File "/Users/nicks/lavoro/TOSS/bria/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-8f4250e639e6>", line 1, in <module>
    ws.cell('A1')
TypeError: cell() missing 1 required positional argument: 'column'

In[43]: ws.cell(1, 'A')
Traceback (most recent call last):
  File "/Users/nicks/lavoro/TOSS/bria/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-4f096d7e4fe5>", line 1, in <module>
    ws.cell(1, 'A')
  File "/Users/nicks/lavoro/TOSS/bria/lib/python3.6/site-packages/openpyxl/worksheet/worksheet.py", line 294, in cell
    if row < 1 or column < 1:
TypeError: '<' not supported between instances of 'str' and 'int'

In[44]: ws.cell(0, 1)
Traceback (most recent call last):
  File "/Users/nicks/lavoro/TOSS/bria/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-44-661da9c0aae5>", line 1, in <module>
    ws.cell(0, 1)
  File "/Users/nicks/lavoro/TOSS/bria/lib/python3.6/site-packages/openpyxl/worksheet/worksheet.py", line 295, in cell
    raise ValueError("Row or column values must be at least 1")
ValueError: Row or column values must be at least 1

In[45]: ws.cell(1, 1)   # <--- this one works
Out[45]: <Cell 's1'.A1>
```

**Comment by daminli** [comment]
Same issue with me:

 cell = ws.cell('%s%s' % (col_idx, row_number)) 
       
       for j, col in enumerate(row):
            #col_idx = get_column_letter(j + 1)
            #cell = ws.cell('%s%s' % (col_idx, row_number))
            cell = ws.cell(row=row_number, column=j + 1)

**Comment by nealdav** [comment]
Same - downgraded openpyxl to 2.4.11 and that seems to work.

**Comment by ant6** [comment]
Same, openpyxl==2.4.11 helped too!

**Comment by wbworks** [comment]
openpyxl < 2.5:
https://github.com/kennethreitz/tablib/blob/4c300e65a50eef72b91fa1909c9f68679723955e/tablib/formats/_xlsx.py#L122
The new way to access [cell with **openpyxl > 2.5.0**](https://openpyxl.readthedocs.io/en/stable/changes.html#id48) is in the concrete case should be:
`cell = ws['%s%s' % (col_idx, row_number)]`

**Comment by iurisilvio** [comment]
Fixed.
